# Generated by Django 5.0.2 on 2024-02-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0002_order_order_number_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
